# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: mysql2
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 3306:3306

    
    
